language: node_js
node_js:
- '4.0'
- '5.0'
- '6.0'
deploy:
  provider: npm
  email: kamil.kisiela@gmail.com
  api_key:
    secure: nFSppLVou9xcm6Q6Sq4oCfGCWUUoVafYeAlKKxiiOOU3XTK1up/nNqcsDGQkFCpA/k9tNNY1qnt5RtEEabbP2DfSE2dRo0FL/FTH389/lrUmdUhF5H9rtYNu/cPJsrBtt7PapexgHUFMzwbfvs/nYxfP5uwnp+yTG55cCVzHDxcWfX8G+ASPDtLqxyMI8yuQ9M4IVUuOTdmi81HoWlqFqPg4cBLmiXton2AGr+D5cPu3cfEYn/x54LeU29CowJ6/wWZHG7lkWgGH4N4acLnCgUzwEURyRqYdKngoex9eEjND2qnldl3N+nILEAZ3fvtTT9FSyWTpGiMwSJU4YsK8ltlaRUfC8TqcawKKlMzjerwhTJU16N74B9Mth99qSdwJI3DLDPmeRynm5+Cmmnx3ps1RAIlvyBbYaCN58QKsfuYrna67omNIMEHFirnprcsKgj0Ywy6qlebQ0wzO7nzvGjkiRvKOut+PHrSC1sT8mLA81GYiRsH0jFFcNputKRmD0+z8XUa47eDZCdkOVp1ps52dDyjq4x2ft3nC+gP8sUDObV7H56nKcS2PDnKqyxpRaup1FM2i01phS8uT18Rj4C3n3E12dKP4psQMbThmAgYZezo9Ohj/IOK0LH9Sgkhmv/Kk97/RimD0LtXaP3E+Gni3+vqzFF2x2WKGfEtp2PM=
